// The utoipa OpenApi derive macro generates code that triggers
// clippy::needless_for_each internally. Suppress at file scope since this is
// a macro code-generation artefact we cannot control.
#![allow(clippy::needless_for_each)]

use utoipa::OpenApi;

use crate::routes::{
    agents, api_keys, audit, auth, auth_logout, auth_password_reset, auth_verify, github, health,
    ingest, mcp, me, query, repos, tenants, tenants::delete as tenant_delete,
    tenants::members as tenant_members,
};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "rust-brain control API",
        description = "Control-plane API for rust-brain: auth, tenant management, API key, GitHub integration, and agent session endpoints.",
        contact(name = "rust-brain", url = "https://github.com/jarnura/rustacean"),
    ),
    paths(
        audit::list_audit_events,
        health::health_check,
        health::ready_check,
        health::consistency_check,
        github::health::github_app_health,
        github::install::github_install_url,
        github::install::github_callback,
        github::repos::list_available_repos,
        auth::signup,
        auth::login,
        auth_logout::logout,
        auth_verify::verify_email,
        auth_password_reset::forgot_password,
        auth_password_reset::reset_password,
        me::get_me,
        me::switch_tenant,
        api_keys::create_api_key,
        api_keys::list_api_keys,
        api_keys::revoke_api_key,
        tenants::list_members,
        tenant_members::invite_member,
        tenant_members::update_member_role,
        tenant_members::remove_member,
        tenant_members::transfer_ownership,
        tenant_delete::delete_tenant,
        repos::connect_repo,
        repos::list_repos,
        repos::trigger_ingest,
        ingest::recent::list_recent_runs,
        ingest::stages::get_stage_timeline,
        ingest::trigger::trigger_ingestion,
        query::graph::post_graph_query,
        query::items::get_item,
        query::modules::get_module_tree,
        query::impls::get_trait_impls,
        query::usages::get_type_usages,
        query::search::search,
        query::traversal::get_callers,
        query::traversal::get_callees,
        agents::sessions::create_session,
        agents::sessions::delete_session,
        agents::session_queries::get_session,
        agents::session_queries::list_sessions,
        agents::events::session_events,
        mcp::mcp_handler,
    ),
    components(
        schemas(
            audit::AuditEventItem,
            audit::AuditListResponse,
            health::ProbeResponse,
            health::HealthResponse,
            health::StoreStatuses,
            health::ConsistencyResponse,
            health::ConsistencyStores,
            health::StoreConsistency,
            github::health::GithubAppHealthResponse,
            github::install::InstallUrlResponse,
            github::repos::RepoItemResponse,
            github::repos::ListReposResponse,
            auth::SignupRequest,
            auth::SignupResponse,
            auth::LoginRequest,
            auth::LoginResponse,
            auth_verify::VerifyEmailRequest,
            auth_password_reset::ForgotPasswordRequest,
            auth_password_reset::ResetPasswordRequest,
            me::MeResponse,
            me::UserInfo,
            me::TenantWithRole,
            me::SwitchTenantRequest,
            me::SwitchTenantResponse,
            me::CurrentTenant,
            api_keys::CreateApiKeyRequest,
            api_keys::CreateApiKeyResponse,
            api_keys::ApiKeyItem,
            api_keys::ListApiKeysResponse,
            tenants::MemberItem,
            tenants::ListMembersResponse,
            tenant_members::InviteMemberRequest,
            tenant_members::InviteMemberResponse,
            tenant_members::UpdateRoleRequest,
            tenant_members::UpdateRoleResponse,
            tenant_members::TransferOwnershipRequest,
            tenant_delete::DeleteTenantResponse,
            repos::ConnectRepoRequest,
            repos::ConnectRepoResponse,
            repos::RepoItem,
            repos::ConnectedReposResponse,
            repos::TriggerIngestResponse,
            ingest::recent::RecentRunItem,
            ingest::recent::RecentRunsResponse,
            ingest::stages::StageRunItem,
            ingest::stages::StageTimelineResponse,
            ingest::trigger::TriggerIngestionRequest,
            ingest::trigger::TriggerIngestionResponse,
            query::graph::GraphQueryRequest,
            query::graph::GraphQueryResponse,
            query::impls::ImplsResponse,
            query::items::ItemResponse,
            query::modules::ModuleTreeResponse,
            query::search::SearchResponse,
            query::traversal::TraversalResponse,
            query::usages::UsagesResponse,
            agents::sessions::CreateSessionRequest,
            agents::sessions::CreateSessionResponse,
            agents::session_queries::SessionItem,
            agents::session_queries::ListSessionsResponse,
            agents::session_queries::SessionDetail,
        )
    ),
    tags(
        (name = "health", description = "Liveness/readiness probes"),
        (name = "audit", description = "Audit trail query"),
        (name = "auth", description = "Authentication"),
        (name = "me", description = "Current user and tenant context"),
        (name = "api-keys", description = "API key management"),
        (name = "tenants", description = "Tenant and membership"),
        (name = "repos", description = "Repository connections"),
        (name = "ingest", description = "Ingestion pipeline"),
        (name = "github", description = "GitHub App integration"),
        (name = "query", description = "Code graph queries"),
        (name = "search", description = "Semantic code search"),
        (name = "agents", description = "Agent session management (ADR-009 Option B)"),
        (name = "mcp", description = "Model Context Protocol endpoint (ADR-009)")
    )
)]
pub struct ApiDoc;

#[expect(dead_code)]
pub fn generate_openapi_spec() -> String {
    ApiDoc::openapi().to_json().expect("OpenAPI serialization")
}
